vim.keymap.set("v", "<leader>mv", function()
  vim.cmd("MoltenEvaluateVisual")
  vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc>", true, false, true), 'n', true)
end, {desc = "Molten Evaluate Visual"})
vim.keymap.set("n", "<leader>ml", function()
  vim.cmd("MoltenEvaluateLine")
end, {desc = "Molten Evaluate Line"})
vim.keymap.set("n", "<leader>jc", "i```python<CR><CR>```", {desc = "Jupyter Create Cell"})
